version: '3.4'

services:
  notiongtdsl:
    image: notiongtdsl
    container_name: notion-gtdsl
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - gtdsl_token_pickle
      - gtdsl_credentials

secrets:
  gtdsl_token_pickle:
    file: token.pickle
  gtdsl_credentials:
    file: credentials.json
