version: "3.4"

services:
  notiongtdsl:
    image: notiongtdsl
    container_name: notion-gtdsl
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./token.pickle:/app/token.pickle
    secrets:
      - gtdsl_credentials

secrets:
  gtdsl_credentials:
    file: credentials.json
